### ISSUE TITLE
Make local URL

### ISSUE THREAD

**Issue by wellemut** [regenduft/mobile.kartevonmorgen#1]
Lieber Florian @regenduft 
Du verwaltest doch die URL für die Domain vonmorgen.org oder?
Könntest du bitte folgende Mappings vornehmen?

Mannheim.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=49.482,8.482&zoom=13.00
Heidelberg.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=49.414,8.692&zoom=13.00
Stuttgart.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=48.787,9.194&zoom=13.00
Bayreuth.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=49.946,11.584&zoom=13.68
Köln.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=50.943,6.966&zoom=13.00
Bonn.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=50.738,7.113&zoom=13.00
Leipzig.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=51.345,12.390&zoom=12.56
Göttingen.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=51.535,9.941&zoom=13.68

Dann könnte ich diese wunderschönen URLs in einen tollen Jahresbericht packen...
Vielen Dank

**Comment by wellemut** [comment]
und heute ganz aktuell
Zürich.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=47.359,8.541&zoom=12.38

**Comment by wellemut** [comment]
@regenduft ach ja und
Lüneburg.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=53.254,10.401&zoom=13.06
Kiel.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=54.324,10.112&zoom=13.06
Darmstadt.vonmorgen.org auf https://www.kartevonmorgen.org/#/?center=49.883,8.637&zoom=13.06

**Comment by regenduft** [comment]
funktioniert jetzt alles.

Zusätzlich

lueneburg.vonmorgen.org
zuerich.vonmorgen.org
goettingen.vonmorgen.org
koeln.vonmorgen.org

**Comment by david-ziegler** [comment]
https://kartevonmorgen.org verweist jetzt auf betterplace. Man muss im Moment "www" explizit angeben um auf die App zu kommen. Kannst du das wieder richtig verlinken? Danke!

**Comment by david-ziegler** [comment]
und: coole sache mit den lokalen URLs :+1:

**Comment by regenduft** [comment]
Ist korrigiert, DNS aktualisiert sich in 900 sekunden.

Ich habe bei der gelegenheit die Umleitung von nicht vergebenen sub-domains nach m.kartevonmorgen.org korrigiert zu www.kartevonmorgen.org

Wenn ich das mache, ersetzt der DNS-Provider die DNS-Einträge automatisch. Und beim zurückkorrigieren habe ich es falsch korrigiert, sorry.

**Comment by regenduft** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}soll kartevonmorgen.org direkt per DNS auf

5.45.109.180 (so wie www.kartenvonmorgen.org)

zeigen, oder ist es besser, wenn es auf einen http-server von meinem DNS-provider geht und der http-server vom DNS einen http redirect zu www.kartevonmorgen.org sendet?

 



ziedavid schrieb am 20.12.2017 13:31:


https://kartevonmorgen.org verweist jetzt auf betterplace. Man muss im Moment "www" explizit angeben um auf die App zu kommen. Kannst du das wieder richtig verlinken? Danke!

**Comment by david-ziegler** [comment]
Danke :) funktioniert wieder.

ja, direkt auf die IP weisen ist gut.

**Comment by wellemut** [comment]
@regenduft Bonn.vonmorgen.org funktioniert nicht!

**Comment by wellemut** [comment]
@regenduft bonn funktioniert doch. Sorry

**Comment by regenduft** [comment]
@wellemut war noch dran. wollte dass bei vertippern z.bsp. obnn.vonmorgen.org etc eine weiterleitung auf www.kartevonmorgen.org passiert und nicht "/ not found" angezeigt wird.

in dem zuge ging zwar weiterhin bonn.vonmorgen.org, aber zunächst www.bonn.vonmorgen.org nicht mehr. Das habe ich wieder hinzugefügt. Sowas wie abc.bonn.vonmorgen.org geht zwar nicht aber das ist wohl wirklich egal.

**Comment by wellemut** [comment]
@regenduft ja, alles klar ja so ist das super.
Ganz vergessen habe ich Berlin.kartevonmorgen.org auf https://www.kartevonmorgen.org/#/?center=52.516,13.418&zoom=11.71

**Comment by regenduft** [comment]
berlin.vonmorgen.org

ich habe es nicht zusätzlich mit von-morgen.org und kartevonmorgen.org und kartevonmorgen.de eingerichtet

Eine automatische umleitung von xxxx.von-morgen.org und xxxx.kartevonmorgen.org und xxxx.kartevonmorgen.de zu xxxx.vonmorgen.org wäre sicher praktisch, leider kann ich das bei meinem hoster nicht konfigurieren, höchstens über uberspace, da könnte ich mich, sollte das gewünscht sein, natürlich drum kümmern.
